Backup/SMS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SMS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome SMS";

            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Backup/SMS/Controllers/SMSAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMSBAL;
using SMS.Models;
using SMSEntities.SMSDBEntities;
using System.IO;
using System.Globalization;
using System.Net.Mail;
using System.Data;
namespace SMS.Controllers
{
    public class SMSAdminController : Controller
    {
        SMSManagementModel objSMSModel = new SMSManagementModel();

        #region Login
        public ActionResult Login()
        {
            return View("../SMSAdmin/LoginView");
        }
        [HttpPost]
        public ActionResult Login(UserInfo p_UserInfo)
        {
            UserInfo objUserInfo = null;
            try
            {
                objUserInfo = objSMSModel.IsUserExists(p_UserInfo);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            if (objUserInfo != null)
            {
                //ViewBag.LoginMsg = string.Empty;
                Session["UserName"] = objUserInfo.UserName;
                Session["UserId"] = objUserInfo.UID;
                Session["UserType"] = objUserInfo.UserTypeID;
                switch (objUserInfo.UserTypeID)
                {
                    case 1: // Super admin
                        Session["DeploymentId"] = objUserInfo.DeploymentID;
                        SMSEntities.SMSDBEntities.Deployement d = objSMSModel.GetDeploymentByID(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), Convert.ToInt32(Session["DeploymentId"]));
                        Session["DeploymentName"] = d.DeploymentName;
                        return RedirectToAction("Deployment");
                    case 2: // Admin
                        Session["DeploymentId"] = objUserInfo.DeploymentID;
                        SMSEntities.SMSDBEntities.Deployement d1 = objSMSModel.GetDeploymentByID(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), Convert.ToInt32(Session["DeploymentId"]));
                        Session["DeploymentName"] = d1.DeploymentName;
                        return RedirectToAction("GetVisitorCheckInOut");
                    case 3: // Supervisor.
                    case 4: //  Guard
                        Session["DeploymentId"] = objUserInfo.DeploymentID;
                        SMSEntities.SMSDBEntities.Deployement d2 = objSMSModel.GetDeploymentByID(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), Convert.ToInt32(Session["DeploymentId"]));
                        Session["DeploymentName"] = d2.DeploymentName;
                        return RedirectToAction("AddVisitorCheckInOut");
                    default:
                        return View("../SMSAdmin/LoginView");
                }


            }
            else
            {
                ModelState.AddModelError("", "");
                return View("../SMSAdmin/LoginView");
            }
        }
        public ActionResult Logout()
        {
            Session["UserName"] = null;
            Session["UserType"] = null;
            Session["DeploymentId"] = null;
            Session["Incidents"] = null;
            Session["Occurrences"] = null;
            Session["Visitors"] = null;

            return RedirectToAction("Login");
        }
        #endregion

        #region Deployment

        public ActionResult Deployment()
        {
            if (Session["UserType"] == null || (Session["UserType"].ToString().Equals("4"))) // Should not allow guard to access this page.
                return View("../SMSAdmin/LoginView");
            return View(objSMSModel.GetDeployements(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), string.Empty));
        }
        [HttpPost]
        public ActionResult Deployment(FormCollection frmCol)
        {
            string searchString = frmCol["txtSearchString"];
            return View(objSMSModel.GetDeployements(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), searchString.Trim()));
        }
        public ActionResult DeploymentEdit(int id)
        {
            if (Session["UserType"] == null || (Session["UserType"].ToString().Equals("4"))) // Should not allow guard to access this page.
                return View("../SMSAdmin/LoginView");
            return View(objSMSModel.GetDeploymentByID(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), id));
        }
        [HttpPost]
        public ActionResult DeploymentEdit(Deployement objDeployement)
        {
            List<Deployement> ds = objSMSModel.GetDeployements(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), String.Empty);

            bool isDeploymentExists = false;
            for (int i = 0; i < ds.Count; i++)
            {
                Deployement d = ds[i];
                if (d.DeploymentId != objDeployement.DeploymentId && d.DeploymentName.Equals(objDeployement.DeploymentName))
                    isDeploymentExists = true;
            }

            if (isDeploymentExists == true)
            {
                ModelState.AddModelError("", "Deployment name already exists. Please enter a different name.");
                return View(objSMSModel.GetDeploymentByID(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), objDeployement.DeploymentId));
            }
            else
            {
                int result = objSMSModel.ModifyDeployment(objDeployement);

                if (result == 1)
                {
                    return RedirectToAction("Deployment");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to update the Deployment now. Please try later");
                    return View(objSMSModel.GetDeploymentByID(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), objDeployement.DeploymentId));
                }
            }
        }

        public ActionResult DeleteDeployment(int ID)
        {
            if (Session["UserType"] == null || (Session["UserType"].ToString().Equals("4"))) // Should not allow guard to access this page.
                return View("../SMSAdmin/LoginView");

            int result = objSMSModel.RemoveDeployment(ID);
            if (result == 1)
            {
                return RedirectToAction("Deployment");
            }
            else
            {
                ModelState.AddModelError("", "Some problem with the Deployment deletion. Please try later.");
                return RedirectToAction("Deployment");
                //return View(objSMSModel.GetDeploymentByID(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), ID));
            }
        }
        public ActionResult DeploymentAdd()
        {
            if (Session["UserType"] == null || (Session["UserType"].ToString().Equals("4"))) // Should not allow guard to access this page.
                return View("../SMSAdmin/LoginView");

            return View(objSMSModel.GetDeploymentByID(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), 0));
        }
        [HttpPost]
        public ActionResult DeploymentAdd(Deployement objDeployement)
        {
            int result = objSMSModel.AddDeployment(objDeployement);
            if (result == 1)
            {
                return RedirectToAction("Deployment");
            }
            else
            {
                ModelState.AddModelError("", "Same deployment " + objDeployement.DeploymentName + " already exists.");
                return View(objSMSModel.GetDeploymentByID(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), 0));
            }
        }

        #endregion

        #region Users
        public ActionResult CreateUser()
        {
            if (Session["UserType"] == null || (Session["UserType"].ToString().Equals("4"))) // Should not allow guard to access this page.
                return View("../SMSAdmin/LoginView");
            return View(objSMSModel.GetUserInfo(Convert.ToInt32(Session["UserType"].ToString()), Convert.ToInt32(Session["DeploymentId"].ToString()), 0));
        }
        [HttpPost]
        public ActionResult CreateUser(FormCollection frmCol)
        {
            UserInfo uinfo = new UserInfo();
            uinfo.UserName = frmCol["UserName"];
            uinfo.Password = frmCol["Password"];
            uinfo.LoginID = frmCol["LoginID"];
            uinfo.EmailID = frmCol["EmailID"];
            //uinfo.DeploymentID = Convert.ToInt32(frmCol["Deployements"].ToString());
            uinfo.UserTypeID = Convert.ToInt32(frmCol["ddlUserTypes"].ToString());

            if (Convert.ToInt32(Session["UserType"].ToString()) == 1)
                uinfo.DeploymentID = Convert.ToInt32(frmCol["Deployements"]);
            else
                uinfo.DeploymentID = Convert.ToInt32(Session["DeploymentId"].ToString());

            int currentUserType = Convert.ToInt32(Session["UserType"].ToString());
            int deploymentId = Convert.ToInt32(Session["DeploymentId"].ToString());
            List<UserViewModel> ds = objSMSModel.GetUsersList(deploymentId, currentUserType, String.Empty);

            bool isUserExists = false;
            for (int i = 0; i < ds.Count; i++)
            {
                UserViewModel d = ds[i];
                if ((!d.UserName.Equals(uinfo.UserName) || !d.EmailID.Equals(uinfo.EmailID)) && d.LoginID.Equals(uinfo.LoginID))
                    isUserExists = true;
            }

            if (isUserExists == true)
            {

Backup/SMS/Views/SMSAdmin/AddLostAndFound.cshtml
@model SMSEntities.SMSDBEntities.LostAndFound
@{
    ViewBag.Title = "AddLostAndFound";
    Layout = "~/Views/Shared/_LayoutTransactions.cshtml";//"~/Views/Shared/_LayoutGuard.cshtml";
}
<h2>
    New Lost And Found</h2>
<script src="../../Scripts/jquery-1.5.1.min.js" type="text/javascript"></script>
@*<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>*@
<link rel="stylesheet" href="@Url.Content("~/Content/css/jquery-ui.css")" />
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.9.1.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui.js")"></script>
<script language="javascript" type="text/javascript">
    function pageValidation() {
        if (document.getElementById("nameofperson").value == "") {
            alert('Please enter the Name');
            document.getElementById("nameofperson").focus();
            return false;
        }
        if (document.getElementById("reporteddate").value == "") {
            alert('Please enter the reported date');
            document.getElementById("reporteddate").focus();
            return false;
        }
        if (document.getElementById("nric").value == "") {
            alert('Please enter the NRIC');
            document.getElementById("nric").focus();
            return false;
        }
        return true;
    }
    $(function () {
        $("#reporteddate").datepicker();
    });
</script>
@using (Html.BeginForm())
{
    <fieldset>
        <div class="check_main_bg_cont">
            <div class="check_left_cont_txt">
                <table>
                    <tr>
                        <td>
                            Name of Person *
                        </td>
                        <td>@Html.TextBoxFor(model => model.nameofperson, new { @class = "bigtextfield" })
                        </td>
                    </tr>
                    <tr>
                        <td>
                            NRIC *
                        </td>
                        <td>@Html.TextBoxFor(model => model.nric, new { @class = "bigtextfield" })
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Date Reported *
                        </td>
                        <td>
                            <input type="text" id="reporteddate" name="reporteddate" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Remarks
                        </td>
                        <td>@Html.TextAreaFor(model => model.remarks, new { @class = "bt" })
                        </td>
                    </tr>
                </table>
                <div style="margin-left: 120px;">
                    <input type="submit" class="btnAddUpdate" value="Add" onclick="return pageValidation();" />
                </div>
            </div>
        </div>
    </fieldset>
}

Backup/SMS/Views/SMSAdmin/AddNewParticipent.cshtml
@model SMSEntities.SMSDBEntities.Visitors
@{
    ViewBag.Title = "AddNewParticipent";
    Layout = "~/Views/Shared/_LayoutTransactions.cshtml";
}
<script language="javascript" type="text/javascript">
    function pageValidation() {
        
         if (document.getElementById("NRIC").value == "") {
            alert('Please enter the NRIC');
            document.getElementById("NRIC").focus();
            return false;
        }
        if (document.getElementById("FirstName").value == "") {
            alert('Please enter the First Name');
            document.getElementById("FirstName").focus();
            return false;
        }
        return true;
    }
</script>
<h2>Add New Participent</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "Please correct the below errors.")
    <fieldset><div class="check_main_bg_cont">
    <div class="check_left_cont_txt">
    <table>
    <tr><td>NRIC: *</td><td>@Html.TextBoxFor(model => model.NRIC, new { @class = "bigtextfield" })</td></tr>
    <tr><td>First Name: *</td><td>@Html.TextBoxFor(model => model.FirstName, new { @class = "bigtextfield" })</td></tr>
    <tr><td>Last Name:</td><td>@Html.TextBoxFor(model => model.LastName, new { @class = "bigtextfield" })</td></tr>
    @*<tr><td>Deployment</td><td>@Html.DropDownListFor(model => Model.Deployements, new SelectList(Model.Deployements, "DeploymentId", "DeploymentName", Model.DeploymentId), "Select", new { @class = "ddl" })</td></tr>*@
    </table>
       
        <div style="margin-left: 120px;">
            <input type="submit" class="btnAddUpdate" value="Add" onclick="return pageValidation();" />
        </div></div>
        </div>
    </fieldset>
}

Backup/SMS/Views/SMSAdmin/Copy of Deployment.cshtml
@model IEnumerable<SMSEntities.SMSDBEntities.Deployement>
@{
    ViewBag.Title = "Deployment";

    var grid = new WebGrid(source: Model,rowsPerPage:3,canPage:true);
}
<h2>
    Deployment</h2>

<p>
@using (Html.BeginForm()){ <b>Search:</b><input type="text" name="txtSearchString" id="txtSearchString" /><input type="submit" class="btnAddUpdate" value="Search" />}
    <div id="dGrid">
        @grid.GetHtml(columns: new[] {
                 grid.Column("DeploymentId"),
                 grid.Column("Description"),
                } )
        <p>@Html.ActionLink("Add New", "AddNewDeployment")</p>

        @grid.GetHtml(
    fillEmptyRows: true,
    alternatingRowStyle: "alternate-row",
    headerStyle: "grid-header",
    footerStyle: "grid-footer",
    mode: WebGridPagerModes.All,
    firstText: "<< First",
    previousText: "< Prev",
    nextText: "Next >",
    lastText: "Last >>",
    columns: new [] {
        
        
        
        grid.Column("DeploymentId", canSort: false),
        grid.Column("Description"),
       
        grid.Column("", 
                    header: "",
                    format: @<text>
                                @Html.ActionLink("Edit", "Edit", new { id = item.DeploymentId })
                                |
                                @Html.ActionLink("Delete", "Delete", new { id = item.DeploymentId })
                            </text>
        )
})
<br />
        <table>
            <tr>
                <th>
                    Sno
                </th>
                <th>
                    Desc
                </th>
            </tr>
            @foreach (var item in Model)
        {
                <tr>
                    <td>@item.Description
                    </td>
                    <td>@Html.ActionLink("Edit", "Edit", new { id = item.DeploymentId })
                    </td>
                    <td>@Html.ActionLink("Delete", "Delete", new { id = item.DeploymentId })
                    </td>
                </tr>
        }
        </table>
    </div>
</p>

Backup/SMS/Views/SMSAdmin/CreateGate.cshtml
@model SMS.Models.GatesViewModel
@{
    ViewBag.Title = "CreateGate";
    Layout = "~/Views/Shared/_LayoutTransactions.cshtml";
}
<script language="javascript" type="text/javascript">
    function pageValidation() {
        if (document.getElementById('Deployments').selectedIndex == 0) {
            alert("Please select Deployment");
            return false;
        }
         if (document.getElementById("GateName").value == "") {
            alert('Please enter the Gate Name');
            document.getElementById("GateName").focus();
            return false;
        }
        return true;
    }
</script>
<h2>
    Create Gate</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "Please correct the below errors.")
    <fieldset><div class="check_main_bg_cont">
        <div class="check_left_cont_txt">
            <div>@ViewBag.ErrMsg</div>
            <table>@if (Session["UserType"] != null && Session["UserType"] != "" && Session["UserType"].ToString().Equals("1"))
                   {
                       <tr><td>Deployment</td><td>@Html.DropDownListFor(model => Model.Deployments, new SelectList(Model.Deployments, "DeploymentId", "DeploymentName", Model.DeploymentId), "Select", new { @class = "ddl" })</td></tr>
                   }
                   <tr><td>Gate name *</td><td>@Html.TextBoxFor(model => model.GateName, new { @class = "bigtextfield" })
            @Html.ValidationMessageFor(model => model.GateName)</td></tr></table>
            
        <div style="margin-left: 120px;">
            <input type="submit" class="btnAddUpdate" value="Create" onclick="return pageValidation();" />
            <a href="@Url.Action("GatesList", "SMSAdmin")"><input type="button"  class="btnCancel" value="Cancel" /></a>
        </div>
        </div>
    </fieldset>
}

Backup/SMS/Views/SMSAdmin/CreateVisitor.cshtml
@model SMS.Models.VisitorsViewModel
@{
    ViewBag.Title = "CreateVisitor";
    Layout = "~/Views/Shared/_LayoutTransactions.cshtml";
}
<script language="javascript" type="text/javascript">
    function pageValidation() {
        if (document.getElementById("FirstName").value == "") {
            alert('Please enter the First Name');
            document.getElementById("FirstName").focus();
            return false;
        }
        return true;
    }
</script>
<h2>
    Create Visitor</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "Please correct the below errors.")
    <fieldset><div class="check_main_bg_cont">
        @*<legend>Create User</legend>*@
        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.FirstName, new { @class = "bigtextfield" })
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.MiddleName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.MiddleName, new { @class = "bigtextfield" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.LastName, new { @class = "bigtextfield" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CompanyName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.CompanyName, new { @class = "bigtextfield" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.ContactNumber)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.ContactNumber, new { @class = "bigtextfield" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Address, new { @class = "bigtextfield" })
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.NRIC)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.NRIC, new { @class = "bigtextfield" })
        </div>
        @if (Session["DeploymentId"] == null)
        {
            <div class="editor-label">
                @Html.LabelFor(model => model.Deployements)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => Model.Deployements, new SelectList(Model.Deployements, "DeploymentId", "DeploymentName", Model.DeploymentId), "--Select--")
            </div>
        }</div>
        <p>
            <input type="submit" class="btnAddUpdate" value="Add" />
        </p>
    </fieldset>
}

Backup/SMS/Views/SMSAdmin/DeleteDeployment.cshtml
@model IEnumerable<SMSEntities.SMSDBEntities.Deployement>
@{
    ViewBag.Title = "Deployments List";
    Layout = "~/Views/Shared/_LayoutTransactions.cshtml";
    var grid = new WebGrid(source: Model, rowsPerPage: 20, canPage: true);
}
<script language="javascript" type="text/javascript">
    function getConfirm() {
        if (window.confirm('Are you sure!, you want to delete?'))
            return true;
        else
            return false;
    }
    function frmSubmit() {
        document.forms[0].submit();
    }
</script>

<div class="Transactions_cont">
  <div class="Displaying_cont_txt" >Deployments</div>
  @using (Html.BeginForm())
  { 
   <div class="transactions_right_cont">
                        <div class="search_txt">
                            search:
                        </div>
                        <div class="wat_box">
                            <input name="txtSearchString" id="txtSearchString" type="text" class="wat_box_input" onfocus="if(this.value == '') this.value = ''"
                                onblur="if(this.value == '') this.value = ' '" value=" " /></div>
                        <div class="search_img" onclick="frmSubmit();">
                        </div>
                    </div>
  }
</div>
    <p>@Html.ActionLink("Add new deployment", "DeploymentAdd")</p>
     @grid.GetHtml(
    fillEmptyRows: true,
         alternatingRowStyle: "transactions_bg_cont_2",
              headerStyle: "transactions_bg_cont",
              rowStyle: "transactions_bg_cont",
         footerStyle: "total_right_cont_txt",
    mode: WebGridPagerModes.All,
    //firstText: "<< First",
    //previousText: "< Prev",
    //nextText: "Next >",
    //lastText: "Last >>",
    numericLinksCount: 5,
    firstText: "<<",
    lastText: ">>",
    columns: new [] {
        
        grid.Column("DeploymentName", "Deployment", canSort: true, style:"normaltext"),
        grid.Column("ClientName", "Client Name", canSort: true, style:"normaltext"),
        grid.Column("Address", "Address", canSort: true, style:"text600"),
        grid.Column("", 
                    //header: "",
                    format: @<text>
                                @Html.ActionLink("Edit", "DeploymentEdit", new { id = item.DeploymentId })
                                |
                                @Html.ActionLink("Delete", "DeleteDeployment", new { id = item.DeploymentId }, new { onclick = "return getConfirm();" })
                            </text>
        )
})
<div class="total_main_bg_cont">
             <div class="total_left_cont_txt">Total Deployments found:<strong> @grid.TotalRowCount.ToString()</strong></div>
             </div>
       

Backup/SMS/Views/SMSAdmin/EditLostAndFound.cshtml
@model SMSEntities.SMSDBEntities.LostAndFound
@{
    ViewBag.Title = "EditLostAndFound";
    Layout = "~/Views/Shared/_LayoutTransactions.cshtml"; //"~/Views/Shared/_LayoutGuard.cshtml";
}
<link rel="stylesheet" href="@Url.Content("~/Content/css/jquery-ui.css")" />
  <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.9.1.js")"></script>
  <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-ui.js")"></script>
<h2>Edit Lost And Found</h2>
<script language="javascript" type="text/javascript">
    function pageValidation() {
        if (document.getElementById("nameofperson").value == "") {
            alert('Please enter the Name');
            document.getElementById("nameofperson").focus();
            return false;
        }
        if (document.getElementById("reporteddate").value == "") {
            alert('Please enter the reported date');
            document.getElementById("reporteddate").focus();
            return false;
        }
        if (document.getElementById("nric").value == "") {
            alert('Please enter the NRIC');
            document.getElementById("nric").focus();
            return false;
        }
        return true;
    }
    $(function () {
        $("#reporteddate").datepicker();
    });

</script>
@using (Html.BeginForm())
{
    <fieldset>
    <div class="check_main_bg_cont">
    <div class="check_left_cont_txt">
    <table>
    <tr><td>Name of Person *</td><td>@Html.TextBoxFor(model => model.nameofperson, (object)new { @readonly = "readonly", @class = "bigtextfield" })
            @Html.HiddenFor(model => model.lostandfoundreportid)</td></tr>
    <tr><td>NRIC *</td><td>@Html.TextBoxFor(model => model.nric, new { @class = "bigtextfield" })</td></tr>
    <tr><td>Date Reported *</td><td>@Html.TextBoxFor(model => model.reporteddate, new { @class = "bigtextfield" })</td></tr>
    <tr><td>Remarks</td><td>@Html.TextAreaFor(model => model.remarks, new { @class = "bt" })</td></tr>
    </table>
        
        <div style="margin-left:120px;">
            <input type="submit" class="btnAddUpdate" value="Update" onclick="return pageValidation();" />
            <a href="@Url.Action("GetLostAndFound", "SMSAdmin")">
                        <input type="button" class="btnCancel" value="Cancel" /></a>
        </div>
        </div>
        </div>
    </fieldset>
}

Backup/SMS/Views/SMSAdmin/GetLocationsList.cshtml
@model IEnumerable<SMS.Models.LocatonViewModel>
@{
    ViewBag.Title = "GetLocationsList";
    Layout = "~/Views/Shared/_LayoutTransactions.cshtml";
    var grid = new WebGrid(source: Model, rowsPerPage: 20, canPage: true);    
}
<script language="javascript" type="text/javascript">
    function getConfirm() {
        if (window.confirm('Are you sure!, you want to delete?'))
            return true;
        else
            return false;
    }
    function frmSubmit() {
        document.forms[0].submit();
    }
</script>
<div class="Transactions_cont">
  <div class="Displaying_cont_txt" >Locations</div>
   @using (Html.BeginForm())
  { 
   <div class="transactions_right_cont">
                        <div class="search_txt">
                            search:
                        </div>
                        <div class="wat_box">
                            <input name="txtSearchString" id="txtSearchString" type="text" class="wat_box_input" onfocus="if(this.value == '') this.value = ''"
                                onblur="if(this.value == '') this.value = ' '" value=" " /></div>
                        <div class="search_img" onclick="frmSubmit();">
                        </div>
                    </div>
  }
</div>
 <p>@Html.ActionLink("Add new location", "CreateLocation")</p>
@grid.GetHtml(
    fillEmptyRows: true,
         alternatingRowStyle: "transactions_bg_cont_2",
              headerStyle: "transactions_bg_cont",
              rowStyle: "transactions_bg_cont",
         footerStyle: "total_right_cont_txt",
    mode: WebGridPagerModes.All,
    //firstText: "<< First",
    //previousText: "< Prev",
    //nextText: "Next >",
    //lastText: "Last >>",
    numericLinksCount: 5,
    firstText: "<<",
    lastText: ">>",
    columns: new [] {
        
        grid.Column("DeploymentName", "Deployment", canSort: true, style:"normaltext"),
        grid.Column("LocationName","Location", canSort: true, style: "normaltext"),
       
        grid.Column("", 
                    header: "",
                    format: @<text>
                                @Html.ActionLink("Edit", "EditLocation", new { id = item.LocationId })
                                |
                                @Html.ActionLink("Delete", "RemoveLocation", new { id = item.LocationId }, new { onclick = "return getConfirm();" })
                            </text>
        )
})
<div class="total_main_bg_cont">
             <div class="total_left_cont_txt">Total Locations found:<strong> @grid.TotalRowCount.ToString()</strong></div>
             </div>